### PR TITLE
Structure for team page

### PR DESCRIPTION
**Pull request by tiltec**
This structure should give us a flexible & translatable team page.

To add members: put a new file in `_members`, with format `name.en.md` (every file in this directory is used, no matter which name)

To refine layout: change `_includes/team.html`. Change css in `css/main.scss`.

@D0nPiano I wasn't really motivated to do a better design. Maybe we include bootstrap? Or some material design library?

### CODE REVIEW

**Comment by nicksellen** [comment]
Can the members be removed from `_config.yml` too, seems duplicated.

**Comment by nicksellen** [comment]
... although I guess there are post authors that might not be team members...

**Comment by nicksellen** [comment]
Oh my it's ugly ;)

**Comment by nicksellen** [comment]
Looks like this now:

team

**Comment by tiltec** [comment]
Oh wow! Pretty amazing! You tend to get trapped in circles on web pages ;)

**Comment by D0nPiano** [comment]
Surprised the other Lars Wolf was a little similar. But now its actually me :D

**Review by D0nPiano — APPROVED** [review]
Looks great! :slightly_smiling_face:

**Comment by D0nPiano** [comment]
@alangecker do you also want to add youself?

**Comment by tiltec** [comment]
What about a short self-description? I'd consider 1-2 sentences nice to have

**Comment by nicksellen** [comment]
Maybe someone can write mildly amusing descriptions for everyone...

**Pull request merged**
